services:
  legacyproxy:
    build: .
    restart: unless-stopped

    ports:
      - "8080:8080"

    volumes:
      - ./data/mitmproxy:/root/.mitmproxy
      - ./data/chrome:/data/chrome

    environment:
      DISPLAY: ":99"